// Encabezado
#include <iostream> // Llamado de librerias
/*Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5,
 * 8, 13, 21, 34, 55, 89,... By considering the terms in the Fibonacci sequence
 * whose values do not exceed four million, find the sum of the even-valued
 * terms. */
int main() {
  // Declaramos variables
  long numero_limite = 4000000;
  long numero_anterior = 1;
  long numero_actual = 2;
  std::cout << numero_anterior << std::endl;
  std::cout << numero_actual << std::endl;

  long numero_siguiente = 0;
  long suma = 2;
  // Desarrollo de la logica
  while (numero_siguiente < numero_limite) // Dentro hay una condición
  {
    numero_siguiente = numero_anterior + numero_actual;
    std::cout << numero_siguiente << std::endl;
    if (numero_siguiente % 2 == 0)
      suma += numero_siguiente;
    // Actualizamos los números
    numero_anterior = numero_actual;
    numero_actual = numero_siguiente;
  }
  std::cout << "La suma de los números pares de Fibonacci es " << suma << "\n";

  return 0;
}