// Encabezado
#include <iostream> // Llamado de librerias
/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */
int main() {
  // Declaramos variables
  int busqueda_fibonacci=0;
  int numero_limite=100;
  int sumatoria=0;
    // Desarrollo de la logica
  for (int busqueda_fibonacci = 1; busqueda_fibonacci < numero_limite;
       busqueda_fibonacci = busqueda_fibonacci + 1) {
// se crea bucle para que entienda hasta cual número debe cálcular los números de la serie de Fibonacci
         int numero_actual=busqueda_fibonacci;
        int numero_siguiente=busqueda_fibonacci+numero_actual;
         std::cout << numero_siguiente<<std::endl;
        sumatoria=sumatoria+numero_siguiente;
       }
  std::cout<<sumatoria;
  return 0;
}